name: Update doc

on: [ workflow_dispatch ]

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master 

      - name: Create doc
        run: cargo doc 

      - name: Move doc
        run: |
          rm -rf ./doc
          mv ./target/doc ./

      - name: Create Pull Request 
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update doc
          labels: Auto PR
          branch: auto-pr/update-doc 
          branch-suffix : timestamp 
          commit-message: update doc
          delete-branch: true
          token: ${{ secrets.AUTO_PR_TOKEN }}

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
